### ISSUE TITLE
ChromeDriver does not match the browser version

### ISSUE THREAD

**Issue by nkjkf** [haq/microsoft-rewards-bot#11]
Hello, I encountered an error when running the script, prompting :
This version of ChromeDriver only supports Chrome version 117
Current browser version is 116.0.5845.180. 
How should I solve this problem? I hope to get your help. Thank you!

**Comment by haq** [comment]
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1558

I will update the image to stop downloading chrome from the Debian repositories.

**Comment by AlterGu** [comment]
I have same issue and waitting author update image :).

**Comment by haq** [comment]
Updated the image.

Everything should be working as before.
