### ISSUE TITLE
 session not created

### ISSUE THREAD

**Issue by jimsaye** [haq/microsoft-rewards-bot#13]
hello u=i have this errors in logs message since today:

rewards_home    |     self.webdriver = self.browserSetup()
rewards_home    |                      ^^^^^^^^^^^^^^^^^^^
rewards_home    |   File "/app/src/browser.py", line 77, in browserSetup
rewards_home    |     driver = webdriver.Chrome(
rewards_home    |              ^^^^^^^^^^^^^^^^^
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
rewards_home    |     super().__init__(*args, **kwargs)
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
rewards_home    |     super(Chrome, self).__init__(
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
rewards_home    |     super().__init__(
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
rewards_home    |     super().__init__(
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 205, in __init__
rewards_home    |     self.start_session(capabilities)
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
rewards_home    |     super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 289, in start_session
rewards_home    |     response = self.execute(Command.NEW_SESSION, caps)["value"]
rewards_home    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 344, in execute
rewards_home    |     self.error_handler.check_response(response)
rewards_home    |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
rewards_home    |     raise exception_class(message, screen, stacktrace)
rewards_home    | selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:47155
rewards_home    | from session not created: This version of ChromeDriver only supports Chrome version 118
rewards_home    | Current browser version is 117.0.5938.149

**Comment by haq** [comment]
Try pulling the latest image and see if it fixes the issue.

**Comment by jimsaye** [comment]
I have the last.

**Comment by haq** [comment]
I pushed a new version of the image, try pulling it to see if it's working. It's working on my system.

**Comment by jimsaye** [comment]
thank's
