### ISSUE TITLE
issue in openwrt docker

### ISSUE THREAD

**Issue by 8056** [haq/microsoft-rewards-bot#16]
![run](https://github.com/haq/microsoft-rewards-bot/assets/60913449/838afe64-123f-4f49-b54a-c0ab2a347b81)
Thank you for your work
when i run the project in the docker in openwrt ， there are something wrong. wish to get your help
the log and img are attached.[](url)

**Comment by 8056** [comment]
[log.txt](https://github.com/haq/microsoft-rewards-bot/files/13402325/log.txt)

**Comment by haq** [comment]
Are you sure your docker installation is working correctly? 

Try running ```docker run hello-world```.

**Comment by 8056** [comment]
> Are you sure your docker installation is working correctly?
> 
> Try running `docker run hello-world`.

When i run hello-world, it is working correctly. Is there any possible that the image can‘t work in armv8 architecture（strawberry pi 3b）?

**Comment by haq** [comment]
Oh ya, the image is only for x86, it is not built for armv8.

**Comment by 8056** [comment]
> Oh ya, the image is only for x86, it is not built for armv8.

Thank you for answering
